#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ("$SHLVL" -eq 1 && ! -o LOGIN) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# 1Password SSH agent.
# https://developer.1password.com/docs/ssh/get-started#step-4-configure-your-ssh-or-git-client
if [[ -e "${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" ]]; then
  export SSH_AUTH_SOCK="${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
fi

# uv
if [[ -s "$HOME/.local/bin/env" ]]; then
  source "$HOME/.local/bin/env"
fi

# Cargo
# https://www.rust-lang.org/tools/install/
export CARGO_HOME="${HOME}/.cargo"
if [[ -s "${CARGO_HOME}/env" ]]; then
  source "${CARGO_HOME}/env"
fi

# Golang
export GOPATH="${HOME}/go"
if [[ -d "${GOPATH}/bin" ]]; then
  export PATH="$PATH:${GOPATH}/bin"
fi

# Rancher Desktop
if [[ -d "/Users/sankichi92/.rd/bin" ]]; then
  export DOCKER_HOST="unix://$HOME/.rd/docker.sock"
  export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
  export TESTCONTAINERS_HOST_OVERRIDE="$(rdctl info --field ip-address 2>/dev/null)"
fi

# brew info postgresql@17
if [[ -d "/opt/homebrew/opt/postgresql@17/bin" ]]; then
  export PATH="$PATH:/opt/homebrew/opt/postgresql@17/bin"
fi
