#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload -Uz +X bashcompinit && bashcompinit

# AWS CLI autocomplete
# https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/cli-configure-completion.html
if (($+commands[aws])); then
  complete -C $(which aws_completer) aws
fi

# Terraform autocomplete (added by `terraform -install-autocomplete`)
if (($+commands[terraform])); then
  complete -o nospace -C $(which terraform) terraform
fi

# 1Password CLI
if [[ -s "${XDG_CONFIG_HOME:-$HOME/.config}/op/plugins.sh" ]]; then
  source "${XDG_CONFIG_HOME:-$HOME/.config}/op/plugins.sh"
fi

# nvm: Calling `nvm use` automatically in a directory with a `.nvmrc` file
# https://github.com/nvm-sh/nvm#calling-nvm-use-automatically-in-a-directory-with-a-nvmrc-file
if (($+commands[nvm])); then
  autoload -U add-zsh-hook

  load-nvmrc() {
    local nvmrc_path
    nvmrc_path="$(nvm_find_nvmrc)"

    if [ -n "$nvmrc_path" ]; then
      local nvmrc_node_version
      nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

      if [ "$nvmrc_node_version" = "N/A" ]; then
        nvm install
      elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
        nvm use
      fi
    elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
      echo "Reverting to nvm default version"
      nvm use default
    fi
  }

  add-zsh-hook chpwd load-nvmrc
  load-nvmrc
fi
